INSERT INTO job_tags (tag_name) VALUES
('NextJS'),
('Flutter'),
('PMP / Agile'),
('Scrum'),
('SEO'),
('Google Ads'),
('Facebook Ads'),
('Content Marketing'),
('Branding'),
('Market Research'),
('AutoCAD'),
('SolidWorks'),
('Revit'),
('PLC'),
('ISO 9001/14001'),
('HSE / An toàn lao động'),
('R&D'),
('Lọc hóa dầu'),
('IFRS'),
('Financial Modeling'),
('M&A'),
('Luật doanh nghiệp'),
('Kế toán tổng hợp'),
('Chứng chỉ phi công (CPL)'),
('TOEIC'),
('Customer Service'),
('Quản lý bếp'),
('SAP'),
('ERP'),
('Supply Chain Planning'),
('Kỹ năng đàm phán')
ON DUPLICATE KEY UPDATE tag_name = tag_name;

INSERT INTO job_categories (category_name) VALUES
('Marketing / Truyền thông'),
('Kinh doanh / Sales'),
('Tài chính / Kế toán'),
('Nhân sự / Tuyển dụng'),
('Kỹ thuật / Sản xuất'),
('Logistics / Chuỗi cung ứng'),
('Hàng không'),
('Xây dựng / Kiến trúc'),
('Du lịch / Khách sạn'),
('Luật / Pháp chế'),
('Nông nghiệp')
ON DUPLICATE KEY UPDATE category_name = category_name;
