-- Replace job tag/category seed data with the new canonical set.
DELETE FROM job_tag_mapping;
DELETE FROM job_category_mapping;
DELETE FROM job_tags;
DELETE FROM job_categories;

INSERT INTO job_tags (tag_id, tag_name) VALUES
    (1, 'Java'), (2, 'Spring Boot'), (3, 'Microservices'),
    (4, 'ReactJS'), (5, 'TypeScript'), (6, 'TailwindCSS'),
    (7, 'NodeJS'), (8, '.NET Core'), (9, 'C#'),
    (10, 'Golang'), (11, 'Python'), (12, 'C++'),
    (13, 'PHP'), (14, 'Laravel'), (15, 'Magento'),
    (16, 'VueJS'), (17, 'JavaScript'), (18, 'HTML/CSS'),
    (19, 'Swift'), (20, 'Kotlin'), (21, 'Flutter'),
    (22, 'Dart'),
    (30, 'SQL'), (31, 'PostgreSQL'), (32, 'Oracle'),
    (33, 'SQL Server'), (34, 'MongoDB'), (35, 'Redis'),
    (36, 'Kafka'), (37, 'Spark'), (38, 'Hadoop'),
    (39, 'ETL'), (40, 'Data Warehouse'), (41, 'PowerBI'),
    (42, 'Tableau'), (43, 'Machine Learning'), (44, 'NLP'),
    (45, 'Computer Vision'), (46, 'PyTorch'), (47, 'AI'),
    (48, 'AWS'), (49, 'Alibaba Cloud'), (50, 'Kubernetes'),
    (51, 'Docker'), (52, 'Terraform'), (53, 'Ansible'),
    (54, 'Jenkins'), (55, 'CI/CD'), (56, 'SRE'),
    (60, 'Cyber Security'), (61, 'SOC'), (62, 'Pentest'),
    (63, 'SIEM'), (64, 'Firewall'), (65, 'IDS/IPS'),
    (66, 'Network Security'), (67, 'CCNA'), (68, 'CCNP'),
    (69, 'Automation Test'), (70, 'Selenium'), (71, 'Appium'),
    (72, 'JMeter'), (73, 'QA'),
    (80, 'Agile'), (81, 'Scrum'), (82, 'PMP'),
    (83, 'Project Management'), (84, 'Product Strategy'),
    (85, 'Roadmap'), (86, 'Requirement Analysis'), (87, 'UML'),
    (88, 'Figma'), (89, 'Prototyping'), (90, 'UX Research'),
    (91, 'Interaction Design'), (92, 'Visual Design'),
    (93, 'Game Logic'), (94, 'Unity'),
    (100, 'Sales'), (101, 'Negotiation'), (102, 'B2B Sales'),
    (103, 'Real Estate'), (104, 'Digital Marketing'), (105, 'SEO'),
    (106, 'Facebook Ads'), (107, 'Google Ads'), (108, 'Branding'),
    (109, 'Content Marketing'), (110, 'Performance Marketing'),
    (111, 'Affiliate Marketing'), (112, 'Finance'), (113, 'Accounting'),
    (114, 'Tax'), (115, 'IFRS'), (116, 'Financial Modeling'),
    (117, 'M&A'), (118, 'Risk Management'),
    (120, 'SAP'), (121, 'ERP'), (122, 'Supply Chain'),
    (123, 'Logistics'), (124, 'Warehouse Management'), (125, 'PLC'),
    (126, 'SCADA'), (127, 'AutoCAD'), (128, 'SolidWorks'),
    (129, 'Revit'), (130, 'FEA'), (131, 'RTOS'),
    (132, 'CAN Bus'), (133, 'Embedded Systems'), (134, 'Battery Tech'),
    (135, 'R&D'), (136, 'Food Safety'), (137, 'QC'),
    (140, 'Pilot License'), (141, 'ICAO'), (142, 'English'),
    (143, 'Customer Service'), (144, 'Recruiting'), (145, 'Tech Sourcing'),
    (146, 'LinkedIn');

INSERT INTO job_categories (category_id, category_name) VALUES
    (1, 'Software Development'),
    (2, 'Data & Analytics'),
    (3, 'Cloud & DevOps'),
    (4, 'AI & Machine Learning'),
    (5, 'Cyber Security'),
    (6, 'UI/UX Design'),
    (7, 'Product Management'),
    (8, 'Project Management'),
    (9, 'Game Development'),
    (10, 'IT Support & Networking'),
    (11, 'Business Analyst'),
    (12, 'Marketing & Communications'),
    (13, 'Sales & Business Development'),
    (14, 'Finance & Accounting'),
    (15, 'Human Resources'),
    (16, 'Engineering & Manufacturing'),
    (17, 'Logistics & Supply Chain'),
    (18, 'Aviation Services'),
    (19, 'Construction & Architecture'),
    (20, 'Legal & Compliance'),
    (21, 'Agriculture & Food Tech');
