ALTER TABLE job_requirements
    ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN modified_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN create_by VARCHAR(50),
    ADD COLUMN modified_by VARCHAR(50);
